/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import javax.swing.*;
import Classes.Connect;
import Classes.ITableUpdate;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Kelok
 */
public class CreateAppointment extends javax.swing.JFrame implements ITableUpdate {

    Statement stmt = null;
    Connection con = null;
    ResultSet rs = null;

    public CreateAppointment() {
        initComponents();
        setLocationRelativeTo(null);
        updateJTable();
        String custQuery = "SELECT * FROM Customer";
        Connect.populateComboBox(appCustCombo, custQuery, "ID");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @Override
    public final void updateJTable() {

        String query = "SELECT * FROM Appointment";
        try {
            con = Connect.ConnectDB();
            stmt = con.createStatement();
            rs = stmt.executeQuery(query);
            appJTable.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        appVetCombo = new javax.swing.JComboBox();
        appCustCombo = new javax.swing.JComboBox();
        appDate = new com.toedter.calendar.JDateChooser();
        createButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appJTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        Date  date = new Date();
        SpinnerDateModel sm = new SpinnerDateModel();
        sm.setCalendarField(Calendar.MINUTE);
        appTime = new javax.swing.JSpinner();
        updateButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        appPetCombo = new javax.swing.JComboBox();
        custLabel = new javax.swing.JLabel();
        petLabel = new javax.swing.JLabel();
        vetLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Set appointment");

        jLabel1.setText("Select Vet ID:");

        jLabel2.setText("Select Customer ID:");

        jLabel3.setText("Date:");

        appVetCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appVetComboActionPerformed(evt);
            }
        });

        appCustCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appCustComboActionPerformed(evt);
            }
        });

        appDate.setDateFormatString("dd/MM/yyyy");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        appJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Vet", "Customer", "Date"
            }
        ));
        appJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(appJTable);

        jLabel4.setText("Time:");

        appTime.setModel(sm);
        JSpinner.DateEditor de = new JSpinner.DateEditor(appTime, "hh:mm a");
        appTime.setEditor(de);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Delete");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Select Pet ID:");

        appPetCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appPetComboActionPerformed(evt);
            }
        });

        custLabel.setText(" ");

        petLabel.setText(" ");

        vetLabel.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(appDate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(appCustCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(appPetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(appVetCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(vetLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(petLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(custLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(appTime, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(712, 712, 712))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(createButton)
                        .addGap(60, 60, 60)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton)
                        .addGap(531, 531, 531))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(appCustCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(custLabel))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(appPetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(petLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(appVetCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(vetLabel))
                                .addGap(18, 18, 18)
                                .addComponent(appDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(appTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelButton)
                            .addComponent(updateButton)
                            .addComponent(createButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setName() {
        String custQuery = "SELECT * FROM Customer WHERE ID = '" + appCustCombo.getSelectedItem() + "'";
        String petQuery = "SELECT * FROM Pet WHERE ID = '" + appPetCombo.getSelectedItem() + "'";
        String vetQuery = "SELECT * FROM Vet WHERE ID = '" + appVetCombo.getSelectedItem() + "'";
        try {
            con = Connect.ConnectDB();
            stmt = con.createStatement();

            rs = stmt.executeQuery(custQuery);
            if (rs.next()) {
                custLabel.setText(rs.getString("Fullname"));
            }

            rs = stmt.executeQuery(petQuery);
            if (rs.next()) {
                petLabel.setText(rs.getString("Fullname"));
            }

            rs = stmt.executeQuery(vetQuery);
            if (rs.next()) {
                vetLabel.setText(rs.getString("Fullname"));
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed

        try {
            String date = new SimpleDateFormat("dd/MM/yyyy").format(appDate.getDate());
            String time = new SimpleDateFormat("hh:mm a").format(appTime.getValue());
            String Query = "INSERT INTO Appointment VALUES ('" + appVetCombo.getSelectedItem() + "','" + appCustCombo.getSelectedItem() + "','" + appPetCombo.getSelectedItem() + "', '"
                    + date + "', '" + time + "')";
            con = Connect.ConnectDB();
            stmt = con.createStatement();
            stmt.execute(Query);
            JOptionPane.showMessageDialog(null, "Appointment added");
            updateJTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void appJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appJTableMouseClicked
        try {
            // TODO add your handling code here:
            int row = appJTable.getSelectedRow();
            String dateString = appJTable.getModel().getValueAt(row, 3).toString();
            String timeString = appJTable.getModel().getValueAt(row, 4).toString();
            Date date = new SimpleDateFormat("dd/MM/yyyy").parse(dateString);
            Date time = new SimpleDateFormat("hh:mm a").parse(timeString);

            appVetCombo.setSelectedItem(appJTable.getModel().getValueAt(row, 0).toString());
            appCustCombo.setSelectedItem(appJTable.getModel().getValueAt(row, 1).toString());
            appPetCombo.setSelectedItem(appJTable.getModel().getValueAt(row, 2).toString());
            appDate.setDate(date);
            appTime.setValue(time);

        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_appJTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        try {
            String date = new SimpleDateFormat("dd/MM/yyyy").format(appDate.getDate());
            String time = new SimpleDateFormat("hh:mm a").format(appTime.getValue());
            String selection = appJTable.getModel().getValueAt(appJTable.getSelectedRow(), 0).toString();
            con = Connect.ConnectDB();
            stmt = con.createStatement();
            String Query = "UPDATE Appointment SET Vet = '" + appVetCombo.getSelectedItem() + "',Customer = '" + appCustCombo.getSelectedItem() + "', Pet = '" + appPetCombo.getSelectedItem() + "', Date = '" + date
                    + "', Time = '" + time + "' WHERE Vet = '" + selection + "'";
            stmt.execute(Query);
            JOptionPane.showMessageDialog(null, "Appointment updated");
            updateJTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());

        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        try {
            String query = "DELETE FROM Appointment WHERE Vet = '" + appVetCombo.getSelectedItem() + "'";
            con = Connect.ConnectDB();
            stmt = con.createStatement();
            stmt.execute(query);
            JOptionPane.showMessageDialog(null, "Appointment deleted");
            updateJTable();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void appCustComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appCustComboActionPerformed
        String query = "SELECT * FROM Pet WHERE OwnerID = '" + appCustCombo.getSelectedItem() + "'";
        Connect.populateComboBox(appPetCombo, query, "ID");
        setName();
    }//GEN-LAST:event_appCustComboActionPerformed

    private void appPetComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appPetComboActionPerformed
        String query_pet = "SELECT * FROM Pet WHERE ID = '" + appPetCombo.getSelectedItem() + "'";
        try {
            con = Connect.ConnectDB();
            stmt = con.createStatement();
            rs = stmt.executeQuery(query_pet);
            if (rs.next()) {
                String pet_type = rs.getString("Type");
                String query_vet = "SELECT * FROM Vet WHERE Expertise = '" + pet_type + "' OR Expertise_2 = '" + pet_type + "'";
                Connect.populateComboBox(appVetCombo, query_vet, "ID");
                setName();
            }
        } catch (SQLException ex) {
            Logger.getLogger(CreateAppointment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_appPetComboActionPerformed

    private void appVetComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appVetComboActionPerformed
        setName();
    }//GEN-LAST:event_appVetComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CreateAppointment().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox appCustCombo;
    private com.toedter.calendar.JDateChooser appDate;
    private javax.swing.JTable appJTable;
    private javax.swing.JComboBox appPetCombo;
    private javax.swing.JSpinner appTime;
    private javax.swing.JComboBox appVetCombo;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel custLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel petLabel;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel vetLabel;
    // End of variables declaration//GEN-END:variables

}
